apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: frontend-wildcard
  namespace: istio-system
spec:
  secretName: frontend-wildcard
  dnsNames:
  - '*.arctiqtim.anthos.labs.arctiq.ca'
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer